#!/bin/bash

# exit when a command fails
set -e

start=$(date +%s)

docker build -t webserv-tester .
docker run webserv-tester

end=$(date +%s)
seconds=$(echo "$end - $start" | bc)
echo
echo
echo "Test done in $(awk -v t=$seconds 'BEGIN{t=int(t*1000); printf "%02d hours, %02d minutes, %02d seconds\n", t/3600000, t/60000%60, t/1000%60}')"

exit 0
